---
title: Timeline profissional
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: steps
  values:
    title: 
    date: 1987-10-17 00:00:00 -0700
markdown: kramdown
highlighter: rouge
lsi: false
description: minha linha do tempo profissional
baseurl: "/timeline"
url: https://cassiodeveloper.com.br/timeline
color: "#f2f2f2"
